version: "3.9"
services:
  postgres:
    image: postgres:11
    environment:
      POSTGRES_DB: "transcriber"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
    ports:
      - "5432:5432"
  vosk:
    image: alphacep/kaldi-en:latest
    ports:
      - "2700:2700"
  ffmpeg:
    image: kazhar/ffmpeg-api
    ports:
      - "3000:3000"